/// ABI for RentPactEscrow, hand-kept in sync with contracts/contracts/RentPactEscrow.sol
/// (Constitution v1.2 — Tier 1 settlement, ratio-split resolution, auto-fallback, and
/// the caution fee escrow/claim/auto-release flow).
export const rentPactEscrowAbi = [
  {
    inputs: [
      { internalType: "address", name: "token_", type: "address" },
      { internalType: "address", name: "arbiter_", type: "address" },
      { internalType: "bytes32", name: "constitutionHash_", type: "bytes32" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AlreadyCancelled", type: "error" },
  { inputs: [], name: "AlreadySigned", type: "error" },
  { inputs: [], name: "ArbitrationWindowNotElapsed", type: "error" },
  { inputs: [], name: "CannotAcceptOwnProposal", type: "error" },
  { inputs: [], name: "CautionAlreadySettled", type: "error" },
  { inputs: [], name: "ClaimAlreadyFiled", type: "error" },
  { inputs: [], name: "ClaimWindowClosed", type: "error" },
  { inputs: [], name: "ClaimWindowNotElapsed", type: "error" },
  { inputs: [], name: "CredentialContractAlreadySet", type: "error" },
  { inputs: [], name: "NotDeployer", type: "error" },
  { inputs: [], name: "DisputeActive", type: "error" },
  { inputs: [], name: "DisputeAlreadyActive", type: "error" },
  { inputs: [], name: "DisputeNotActive", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidBps", type: "error" },
  { inputs: [], name: "InvalidClaimAmount", type: "error" },
  { inputs: [], name: "InvalidPeriods", type: "error" },
  { inputs: [], name: "LeaseFullyReleased", type: "error" },
  { inputs: [], name: "LeaseNotComplete", type: "error" },
  { inputs: [], name: "LeaseNotFound", type: "error" },
  { inputs: [], name: "LeaseNotSigned", type: "error" },
  { inputs: [], name: "NoCautionFee", type: "error" },
  { inputs: [], name: "NoEvidence", type: "error" },
  { inputs: [], name: "NoPeriodsElapsed", type: "error" },
  { inputs: [], name: "NoRepairCreditOffer", type: "error" },
  { inputs: [], name: "NoSettlementProposal", type: "error" },
  { inputs: [], name: "InvalidCreditAmount", type: "error" },
  { inputs: [], name: "RepairCreditOnCautionClaim", type: "error" },
  { inputs: [], name: "NotArbiter", type: "error" },
  { inputs: [], name: "NotLandlord", type: "error" },
  { inputs: [], name: "NotParty", type: "error" },
  { inputs: [], name: "NotTenant", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "SettlementWindowClosed", type: "error" },
  { inputs: [], name: "SettlementWindowNotClosed", type: "error" },
  { inputs: [], name: "SignDeadlineNotPassed", type: "error" },
  { inputs: [], name: "SignDeadlinePassed", type: "error" },
  { inputs: [], name: "ZeroAddress", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint16", name: "landlordBps", type: "uint16" },
      { indexed: false, internalType: "uint256", name: "releasedToLandlord", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "refundedToTenant", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "resolutionType", type: "uint8" },
    ],
    name: "CautionClaimResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "CautionReleased",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "claimAmount", type: "uint256" },
      { indexed: false, internalType: "bytes32", name: "evidenceHash", type: "bytes32" },
      { indexed: false, internalType: "uint256", name: "remainderReleased", type: "uint256" },
    ],
    name: "DepositClaimFiled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: true, internalType: "address", name: "tenant", type: "address" },
      { indexed: false, internalType: "string", name: "reason", type: "string" },
    ],
    name: "DisputeRaised",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint16", name: "landlordBps", type: "uint16" },
      { indexed: false, internalType: "uint256", name: "releasedToLandlord", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "refundedToTenant", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "resolutionType", type: "uint8" },
    ],
    name: "DisputeResolved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "refundedAmount", type: "uint256" },
    ],
    name: "LeaseCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "LeaseCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: true, internalType: "address", name: "tenant", type: "address" },
      { indexed: true, internalType: "address", name: "landlord", type: "address" },
      { indexed: false, internalType: "uint256", name: "amountPerPeriod", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalPeriods", type: "uint256" },
      { indexed: false, internalType: "uint8", name: "frequency", type: "uint8" },
      { indexed: false, internalType: "uint256", name: "rentDeposited", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "cautionAmount", type: "uint256" },
    ],
    name: "LeaseCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "signedAt", type: "uint256" },
    ],
    name: "LeaseSigned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: true, internalType: "address", name: "proposer", type: "address" },
      { indexed: false, internalType: "uint16", name: "landlordBps", type: "uint16" },
    ],
    name: "SettlementProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RepairCreditOffered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RepairCreditAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "RepairCreditWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "leaseId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "periodsReleased", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amountReleased", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "totalPeriodsReleased", type: "uint256" },
    ],
    name: "TrancheReleased",
    type: "event",
  },
  {
    inputs: [],
    name: "ARBITRATION_WINDOW",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BPS_DENOMINATOR",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CAUTION_CLAIM_WINDOW",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SETTLEMENT_WINDOW",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SIGN_DEADLINE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "acceptSettlement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "arbiter",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "autoResolveOverdueDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "cancelUnsigned",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "constitutionHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "credentialContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "deployer",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "credentialContract_", type: "address" }],
    name: "setCredentialContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "landlord", type: "address" },
      { internalType: "uint256", name: "amountPerPeriod", type: "uint256" },
      { internalType: "uint256", name: "periods", type: "uint256" },
      { internalType: "uint8", name: "frequency", type: "uint8" },
      { internalType: "uint256", name: "cautionAmount", type: "uint256" },
    ],
    name: "createLease",
    outputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "leaseId", type: "uint256" },
      { internalType: "uint256", name: "claimAmount", type: "uint256" },
      { internalType: "bytes32", name: "evidenceHash", type: "bytes32" },
    ],
    name: "fileDepositClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "releaseCaution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "getLease",
    outputs: [
      {
        components: [
          { internalType: "address", name: "tenant", type: "address" },
          { internalType: "address", name: "landlord", type: "address" },
          { internalType: "uint256", name: "amountPerPeriod", type: "uint256" },
          { internalType: "uint256", name: "totalPeriods", type: "uint256" },
          { internalType: "uint256", name: "periodsReleased", type: "uint256" },
          { internalType: "uint8", name: "frequency", type: "uint8" },
          { internalType: "uint256", name: "createdAt", type: "uint256" },
          { internalType: "uint256", name: "signedAt", type: "uint256" },
          { internalType: "bool", name: "signed", type: "bool" },
          { internalType: "bool", name: "cancelled", type: "bool" },
          { internalType: "bool", name: "disputeActive", type: "bool" },
          { internalType: "uint256", name: "disputeRaisedAt", type: "uint256" },
          { internalType: "string", name: "disputeReason", type: "string" },
          { internalType: "uint16", name: "settlementProposedBps", type: "uint16" },
          { internalType: "address", name: "settlementProposer", type: "address" },
          { internalType: "uint256", name: "repairCreditHeld", type: "uint256" },
          { internalType: "bool", name: "disputeIsCautionClaim", type: "bool" },
          { internalType: "uint256", name: "cautionAmount", type: "uint256" },
          { internalType: "uint256", name: "completedAt", type: "uint256" },
          { internalType: "uint256", name: "cautionClaimedAmount", type: "uint256" },
          { internalType: "bytes32", name: "cautionClaimEvidenceHash", type: "bytes32" },
          { internalType: "uint256", name: "cautionClaimFiledAt", type: "uint256" },
          { internalType: "bool", name: "cautionSettled", type: "bool" },
          { internalType: "bool", name: "completedNaturally", type: "bool" },
          { internalType: "uint256", name: "latePeriods", type: "uint256" },
          { internalType: "uint256", name: "disputesLostCount", type: "uint256" },
          { internalType: "uint256", name: "credentialTokenId", type: "uint256" },
        ],
        internalType: "struct RentPactEscrow.Lease",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "frequency", type: "uint8" }],
    name: "intervalSeconds",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "pendingPeriods",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "leaseId", type: "uint256" },
      { internalType: "uint16", name: "landlordBps", type: "uint16" },
    ],
    name: "proposeSettlement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "leaseId", type: "uint256" },
      { internalType: "uint256", name: "creditAmount", type: "uint256" },
    ],
    name: "offerRepairCredit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "acceptRepairCredit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "withdrawRepairCredit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "leaseId", type: "uint256" },
      { internalType: "string", name: "reason", type: "string" },
    ],
    name: "raiseDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "releaseTranche",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "leaseId", type: "uint256" },
      { internalType: "uint16", name: "landlordBps", type: "uint16" },
    ],
    name: "resolveDispute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "leaseId", type: "uint256" }],
    name: "signLease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "token",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const erc20Abi = [
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
